name: AccountLock
main: AC\Main
version: "1.1_Beta"
api: [1.12.0]
load: POSTWORLD
author: SavionLegendZzz
commands:
 lockacc:
  permission: ac.command.ac
  description: AccountLock Plugin Main Command
 unlockacc:
  permission: ac.command.ac
  description: AccountLock Plugin Main Command
